spring:
  jpa:
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL81Dialect


  datasource:
    driver-class-name: org.postgresql.Driver
    username: user
    password: password
    url: jdbc:postgresql://localhost:5432/clinic_db

  flyway:
    enabled: true
    baseline-version: 0
    baseline-on-migrate: true


  graphql:
    graphiql:
      enabled: true

server:
  port: 8080
  shutdown: graceful
